project:
  type: website
  output-dir: C:\Users\Si Ming\Documents\GitHub\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Conservation.qmd
        text: Conservation
      - href: Wildfire_management.qmd
        text: Wildfire management

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

