project:
  type: website
  output-dir: C:/Users/siming01.stu/Documents/GitHub/E-Portfolio

website:
  title: "Si Ming's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Conservation.qmd
        text: Conservation
      - href: Wildfire_management.qmd
        text: Wildfire management

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

editor: visual

